# Whenever a tag push matching pattern "v*" then run the job
on: 
  push:
    branches:
      - main
  workflow_dispatch:

env:
  BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
  ITCH_GAME: "godot-wild-jam-63-title-tbd"
  ITCH_USER: "pyrious"

jobs:
  # job id, can be anything
  compile_and_upload: # we need to be sequential with our jobs ;_;
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: checkout
      uses: actions/checkout@v3.3.0
  
    - name: export game
      id: export
      # Use latest version (see releases for all versions)
      uses: firebelley/godot-export@v5.2.0
      with:
        # Defining all the required inputs
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.1.2/Godot_v4.1.2-stable_linux.x86_64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.1.2/Godot_v4.1.2-stable_export_templates.tpz
        relative_project_path: ./
        cache: true
        
    - name: upload windows
      uses: manleydev/butler-publish-itchio-action@master
      with:
        CHANNEL: windows
        PACKAGE: build/windows
    - name: upload macos
      uses: manleydev/butler-publish-itchio-action@master
      with:
        CHANNEL: macos
        PACKAGE: build/mac
    - name: upload linux
      uses: manleydev/butler-publish-itchio-action@master
      with:
        CHANNEL: linux
        PACKAGE: build/linux
    - name: upload html5
      uses: manleydev/butler-publish-itchio-action@master
      with:
        CHANNEL: html
        PACKAGE: build/web

    # skip producing a release and just directly upload the artifacts??
    #   # This release action has worked well for me. However, you can most likely use any release action of your choosing.
    #   # https://github.com/ncipollo/release-action
    # - name: create release
    #   uses: ncipollo/release-action@v1.12.0
    #   with:
    #     token: ${{ secrets.GITHUB_TOKEN }}
    #     generateReleaseNotes: true
    #     tag: ${{ github.ref_name }}
    #     artifacts: ${{ steps.export.outputs.archive_directory }}/*
