name: Build + Publish Game

on:
  push:
    branches: main
  workflow_dispatch:

env:
  G_ITCH_PAGE: "godot-wild-jam-63-title-tbd"
  G_ITCH_ACCOUNT: "pyrious"

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - name: "windows"
            output: "game_windows.exe"
          - name: "linux"
            output: "game_linux.x86_64"
          - name: "mac"
            output: "game_mac.zip"
          - name: "web"
            output: "index.html"
    container:
      image: barichello/godot-ci:4.1.2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true # do we really need LFS??
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
        env:
          GODOT_VERSION: 4.1.2
      - name: Build
        run: |
          mkdir -v -p build/${{ matrix.platform.name }}
          godot -v --headless --export-release ${{ matrix.name}}  ./build/${{ matrix.name }}/${{ matrix.output }}
      - name: Deploy to Itch
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: ${{ matrix.name }}
          ITCH_GAME: ${{ env.G_ITCH_PAGE }}
          ITCH_USER: ${{ env.G_ITCH_ACCOUNT }}
          PACKAGE: build/${{ matrix.name }}/
